<a href="https://colab.research.google.com/github/andresvosa/testNotebooks/blob/main/LinearsystemExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from sympy.interactive import printing
printing.init_printing(use_latex=True)
from sympy import Eq, solve_linear_system, Matrix
from numpy import linalg
import sympy as sp
import numpy as np

In [16]:
print('Using Sympy')
eq1 = sp.Function('eq1')
eq2 = sp.Function('eq2')

x, y = sp.symbols('x y')
eq1 = Eq(2*x-y, -4)
eq2 = Eq(3*x-y, -2)
display(eq1)
display(eq2)

row1 = [2, -1, -4]
row2 = [3, -1, -2]

system1 = Matrix((row1, row2))
display(system1)

display(solve_linear_system(system1, x, y))



Using Sympy


⎡2  -1  -4⎤
⎢         ⎥
⎣3  -1  -2⎦

In [17]:
print('Using Numpy')
nprow1 = [2, -1]
nprow2 = [3, -1]
nmat = np.array([nprow1, nprow2])
display(nmat)
cons = np.array([-4, -2])
display(cons)

answer = linalg.solve(nmat, cons)
display(answer)
xval = answer[0]
yval = answer[1]

print(f'x = {xval}')
print(f'y = {yval}')

Using Numpy


array([[ 2, -1],
       [ 3, -1]])

array([-4, -2])

array([2., 8.])

x = 2.0
y = 8.0
