<a href="https://colab.research.google.com/github/andresvosa/testNotebooks/blob/main/lpassdiscrete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from scipy import signal
import numpy as np


In [2]:
# Continous transfer function for low pass filter
w0 = 2 * np.pi * 5  # Cutting frequency 5Hz
num = w0
den = [1, w0]
lowpass = signal.TransferFunction(num, den)
print(lowpass)


TransferFunctionContinuous(
array([31.41592654]),
array([ 1.        , 31.41592654]),
dt: None
)


In [3]:
# Discrete transfer function
dt = 1.0 / 1000.0 # Timestep 1/fs, fs-sampling frequency
disclowpass = lowpass.to_discrete(dt, method='gbt', alpha=0.5)
print(disclowpass)


TransferFunctionDiscrete(
array([0.01546504, 0.01546504]),
array([ 1.        , -0.96906992]),
dt: 0.001
)


In [4]:
# Difference equation coefficients
b = disclowpass.num
a = - disclowpass.den
print('filter coefficients bi: ' + str(b))  
print('filter coefficients ai: ' + str(a[1:]))


filter coefficients bi: [0.01546504 0.01546504]
filter coefficients ai: [0.96906992]


In [5]:
# Y[n] = a1*Y[n-1]+...b0*X[n]+b1*X[n-1]...
# Y[n] = 0.969*Y[n-1]+0.0155*X[n]+0.0155*X[n-1]
# Y-filtered signal
# X-raw signal
